  //type
#define TYPE_STRING_VIEW 0
#define TYPE_STRING_WRITE 1

  //update type
//UI container
#define UPDATE_SET_HEAD 0
#define UPDATE_SET_HEAD_COLOR 1
#define UPDATE_SET_HEAD_BACKGROUND_COLOR 2

//StringView
#define UPDATE_SET_TEXT 3
#define UPDATE_SET_TEXT_COLOR 4
#define UPDATE_SET_TEXT_BACKGROUND_COLOR 5

//StringWrite
#define UPDATE_SET_HINT 3
#define UPDATE_SET_BACKGROUND_COLOR 4

  //size
#define STRING_VIEW_BYTE_DATA 600
#define STRING_VIEW_BYTE_UPDATE 1000
#define STRING_VIEW_BYTE_ALL_UPDATE 2501